package ua.snuk182.asia.services.api;

public enum ServiceResponse {
	NOP,
	SAVE_PARAMS,
	CONNECTED,
	DISCONNECTED,
	STATUS_SET,
	EXTENDED_STATUS_SET,
	MESSAGE,
	FILE_MESSAGE,
	USER_INFO,
	OWN_INFO,
	OWN_INFO_SET,
	BUDDY_ADDED,
	BUDDY_DELETED,
	CL_UPDATED,
	BUDDY_STATE_CHANGED,
	SAVE_IMAGE_FILE,
	NOTIFICATION,
	ACCOUNT_UPDATED,
	SAVE_TO_STORAGE,
	GET_FROM_STORAGE,
	AUTH_REQUEST,
	SEARCH_RESULT,
	BUDDY_MODIFIED,
	GROUP_MODIFIED,
	GROUP_ADDED,
	GROUP_DELETED,
	
	/**
	 * Connection establishing state. Args = {int progress (range 0..10)}
	 */
	CONNECTING,
	FILE_PROGRESS,
	VISUAL_STYLE,
	ACCOUNT_REMOVED,
	ACCOUNT_ADDED,
	MESSAGE_ACK,
	TYPING,
	AVAILABLE_CHATS,
	CHAT_PARTICIPANTS,
	SERVICE_MESSAGE
}
